[workspace]
preview = ["pixi-build"]
authors = ["Slava Chaunin <67190162+Ssslakter@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "stargine"
platforms = ["linux-64"]
version = "0.1.0"

[tasks.app]
cmd = "mojo main.mojo"
env = { ROOT_DIR = "./stargine", SDL_VIDEODRIVER="wayland" }

[tasks.test]
args = [{"arg"="folder"}]
cmd = "./tests/run_test.sh {{folder}}"

[dependencies]
mojo = ">=1.1.0.dev2026082605"
opengl-mojo = { git = "https://github.com/MojoGameDevs/opengl-mojo.git", tag = "v0.1.0" }
sdl-mojo = { git = "https://github.com/MojoGameDevs/sdl-mojo.git" }
ipykernel = ">=6.29.5,<7"
pillow = ">=12.1.0,<13"
numpy = ">=2.4.0,<3"
